### PR TITLE
Move liaisons.md to community repo

### PR DESCRIPTION
**Pull request by nikhita**
As discussed in yesterday's (18 Jan 2020) private SC meeting ([notes](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit#heading=h.37nbij36msqa)).

Ref: https://github.com/kubernetes/community/pull/5415, adds support for liaisons in sigs.yaml directly

/hold
until https://github.com/kubernetes/community/pull/5415 merges

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm

once other PR merges

**Comment by liggitt** [comment]
oh, also need to update onboarding doc, right?

**Comment by nikhita** [comment]
> oh, also need to update onboarding doc to point to the source of the assignments, right?

we already had a point about updating sigs.yaml, added a note about liaisons next to it :+1:

**Comment by nikhita** [comment]
/hold cancel
https://github.com/kubernetes/community/pull/5415 has merged

**Pull request merged**
