### PR TITLE
Detail election officer schedule and criteria

### PR DESCRIPTION
**Pull request by spiffxp**
Fixes https://github.com/kubernetes/steering/issues/75

Addresses the first two items of https://github.com/kubernetes/steering/issues/78

### CODE REVIEW

**Comment by dims** [comment]
/lgtm
/hold 

(please remove hold when appropriate)

**Comment by spiffxp** [comment]
lazy consensus: https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/JzZcjWqe2-c

holding until COB (PT) tomorrow

**Comment by idvoretskyi** [comment]
PTAL @parispittman @castrojo

**Comment by parispittman** [comment]
lgtm

**Comment by spiffxp** [comment]
/hold cancel
lazy consensus deadline passed

**Pull request merged**
