### PR TITLE
Create values.md

### PR DESCRIPTION
**Pull request by sarahnovotny**
draft values.md file for comment

### CODE REVIEW

**Comment by shtatfeld** [comment]
I think you captured very well the community values. Thank you! I have a proposal to add User focus as a value. I think we have been thinking of our users, being pragmatic and solving real problems. Building a viable OSS technology. Investing in ease of use and more. It is captured right now in: Community over product or company, but maybe deserves to be called out as value of its own.

**Comment by jbeda** [comment]
+1 merge it!

**Comment by smarterclayton** [comment]
+1 lgtm

**Comment by michelleN** [comment]
+1 awesome. thanks!

**Comment by quinton-hoole** [comment]
+1

**Comment by jbeda** [comment]
Calling lazy consensus and giving this a LGTM.

/lgtm

**Pull request merged**
