### PR TITLE
CNCF Representative added

### PR DESCRIPTION
**Pull request by idvoretskyi**
/assign @nikhita @parispittman @cblecker 

Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>

### CODE REVIEW

**Comment by idvoretskyi** [comment]
Fixes - https://github.com/kubernetes/steering/pull/148.

**Comment by dims** [comment]
/hold

wait for a few more folks to peek at this.

**Comment by nikhita** [comment]
Lgtm :+1:

**Comment by cblecker** [comment]
/hold cancel

That's 5 :)

**Pull request merged**
