### PR TITLE
Document process changes to steering committee governance

### PR DESCRIPTION
**Pull request by derekwaynecarr**
The following captures in words what was discussed in our past meetings.

The procedure allows for 4 weeks when making significant changes to governance.  Changes are lazily approved after 4 weeks if no-one calls for a vote.  If a vote is requested, changes are passed with 3/4 majority.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@timothysc @smarterclayton

**Comment by brendandburns** [comment]
LGTM.

**Comment by jbeda** [comment]
We are going to try and get a LGTM from all committee members.

/lgtm

**Comment by bgrant0607** [comment]
For posterity, the modified lazy consensus seeking discussion doc:
https://docs.google.com/document/d/1fRYZYQlCGv4ebMqwZE8BRzPbuGl8ElyaNr5CuEmaRyk/edit

**Pull request merged**
